# Generated by Django 4.2.7 on 2023-11-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovarimage',
            name='tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='tovar.tovar'),
        ),
    ]
